### ISSUE TITLE
In /search/find_dggs_by_geojson return DGGS cell ID in the first position

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/AusPIX_DGGS_API#36]
"Could the DGGS cell ID be in the first column please (rather than the last)?"

Can the ordering of the cell_id be such that it is the first item in the properties dict in the returned geojson?

**Comment by jyucsiro** [comment]
Looks like #37 has fixed it @jevy-wangfei ?

**Comment by jevy-wangfei** [comment]
Yes, it is.
